version: '3.7'
services:
  db:
    image: postgres:17
    container_name: postgres_db
    deploy:
      resources:
        limits:
          memory: 2g
    shm_size: '2gb'             # Set shared memory size to 1GB
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo18@2024
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo18:
    image: odoo:18
    depends_on:
      - db
    ports:
      - "10018:8069"
      - "20018:8072"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo18@2024
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
